import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import Image from "next/image";
import Header from "@/components/Header";

const ptRootUi = localFont({
  src: [
    {
      path: "./fonts/pt-root-ui_light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/pt-root-ui_regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/pt-root-ui_medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/pt-root-ui_bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pt-root",
});

const actay = localFont({
  src: [
    {
      path: "./fonts/ActayCondensed-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/ActayCondensed-ThinItalic.otf",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/Actay-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Actay-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/ActayWide-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/ActayWide-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-actay",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ptRootUi.variable} ${actay.variable} antialiased relative`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
